### ISSUE TITLE
[FEAT] 냉장고 UI

### ISSUE THREAD

**Issue by arinming** [NAENG-MEH-CHU/naeng-meh-chu-app#14]
## ✏️ Description
냉장고 UI를 구현합니다 

## To-Do List
- [x] 냉장/냉동 보관
- [x] 바텀 버튼
- [x] 재료 이미지 컴포넌트
- [ ] 더보기 확장 컴포넌트
