### ISSUE TITLE
[FEAT] 회원가입 UI 구현

### ISSUE THREAD

**Issue by arinming** [NAENG-MEH-CHU/naeng-meh-chu-app#8]
## ✏️ Description
회원가입 UI를 구현합니다.

## To-Do List
- [x] 프로필 사진 선택
- [x] 닉네임 설정
- [x] 성별, 나이 설정
- [x] 냉메추 동기 설정
- [x] 회원가입 완료 화면
